### ISSUE TITLE
Отрефакторить переменные

### ISSUE THREAD

**Issue by unrefan** [mikl7/tracking-expenses#13]
https://github.com/mikl7/tracking-expenses/blob/a763cd76e8b0afffe744dcf640e5cc035be38359/resources/views/costs/index.blade.php#L8

нужно поправить названия переменных по всему проекту 
к примеру выше инстанс бюджета записывается в бюджеты - поправить

переменные должны логически быть осмыслены и называться так чтобы было понятно читающему что в ней находится

**Comment by mikl7** [comment]
performed
